/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as PublicRouteImport } from './routes/_public'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as PublicIndexRouteImport } from './routes/_public.index'
import { Route as AdminVariantsRouteImport } from './routes/admin.variants'
import { Route as AdminTemplatesRouteImport } from './routes/admin.templates'
import { Route as AdminTablesRouteImport } from './routes/admin.tables'
import { Route as AdminSettingsRouteImport } from './routes/admin.settings'
import { Route as AdminReviewsRouteImport } from './routes/admin.reviews'
import { Route as AdminReservationsRouteImport } from './routes/admin.reservations'
import { Route as AdminMenuRouteImport } from './routes/admin.menu'
import { Route as AdminGalleryRouteImport } from './routes/admin.gallery'
import { Route as AdminCategoriesRouteImport } from './routes/admin.categories'
import { Route as AdminAuditRouteImport } from './routes/admin.audit'
import { Route as PublicReservationRouteImport } from './routes/_public.reservation'
import { Route as PublicMenuRouteImport } from './routes/_public.menu'
import { Route as PublicGalleryRouteImport } from './routes/_public.gallery'
import { Route as PublicContactRouteImport } from './routes/_public.contact'
import { Route as MenuTableTableIdRouteImport } from './routes/menu.table.$tableId'
import { Route as ApiPublicSyncReviewsRouteImport } from './routes/api.public.sync-reviews'
import { Route as ApiPublicProxyVideoRouteImport } from './routes/api.public.proxy.video'
import { Route as ApiPublicProxyImageRouteImport } from './routes/api.public.proxy.image'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicRoute = PublicRouteImport.update({
  id: '/_public',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const PublicIndexRoute = PublicIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PublicRoute,
} as any)
const AdminVariantsRoute = AdminVariantsRouteImport.update({
  id: '/variants',
  path: '/variants',
  getParentRoute: () => AdminRoute,
} as any)
const AdminTemplatesRoute = AdminTemplatesRouteImport.update({
  id: '/templates',
  path: '/templates',
  getParentRoute: () => AdminRoute,
} as any)
const AdminTablesRoute = AdminTablesRouteImport.update({
  id: '/tables',
  path: '/tables',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminReviewsRoute = AdminReviewsRouteImport.update({
  id: '/reviews',
  path: '/reviews',
  getParentRoute: () => AdminRoute,
} as any)
const AdminReservationsRoute = AdminReservationsRouteImport.update({
  id: '/reservations',
  path: '/reservations',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMenuRoute = AdminMenuRouteImport.update({
  id: '/menu',
  path: '/menu',
  getParentRoute: () => AdminRoute,
} as any)
const AdminGalleryRoute = AdminGalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCategoriesRoute = AdminCategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAuditRoute = AdminAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => AdminRoute,
} as any)
const PublicReservationRoute = PublicReservationRouteImport.update({
  id: '/reservation',
  path: '/reservation',
  getParentRoute: () => PublicRoute,
} as any)
const PublicMenuRoute = PublicMenuRouteImport.update({
  id: '/menu',
  path: '/menu',
  getParentRoute: () => PublicRoute,
} as any)
const PublicGalleryRoute = PublicGalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => PublicRoute,
} as any)
const PublicContactRoute = PublicContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => PublicRoute,
} as any)
const MenuTableTableIdRoute = MenuTableTableIdRouteImport.update({
  id: '/menu/table/$tableId',
  path: '/menu/table/$tableId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicSyncReviewsRoute = ApiPublicSyncReviewsRouteImport.update({
  id: '/api/public/sync-reviews',
  path: '/api/public/sync-reviews',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicProxyVideoRoute = ApiPublicProxyVideoRouteImport.update({
  id: '/api/public/proxy/video',
  path: '/api/public/proxy/video',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicProxyImageRoute = ApiPublicProxyImageRouteImport.update({
  id: '/api/public/proxy/image',
  path: '/api/public/proxy/image',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof PublicIndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/login': typeof LoginRoute
  '/contact': typeof PublicContactRoute
  '/gallery': typeof PublicGalleryRoute
  '/menu': typeof PublicMenuRoute
  '/reservation': typeof PublicReservationRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/gallery': typeof AdminGalleryRoute
  '/admin/menu': typeof AdminMenuRoute
  '/admin/reservations': typeof AdminReservationsRoute
  '/admin/reviews': typeof AdminReviewsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/tables': typeof AdminTablesRoute
  '/admin/templates': typeof AdminTemplatesRoute
  '/admin/variants': typeof AdminVariantsRoute
  '/admin/': typeof AdminIndexRoute
  '/api/public/sync-reviews': typeof ApiPublicSyncReviewsRoute
  '/menu/table/$tableId': typeof MenuTableTableIdRoute
  '/api/public/proxy/image': typeof ApiPublicProxyImageRoute
  '/api/public/proxy/video': typeof ApiPublicProxyVideoRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/contact': typeof PublicContactRoute
  '/gallery': typeof PublicGalleryRoute
  '/menu': typeof PublicMenuRoute
  '/reservation': typeof PublicReservationRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/gallery': typeof AdminGalleryRoute
  '/admin/menu': typeof AdminMenuRoute
  '/admin/reservations': typeof AdminReservationsRoute
  '/admin/reviews': typeof AdminReviewsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/tables': typeof AdminTablesRoute
  '/admin/templates': typeof AdminTemplatesRoute
  '/admin/variants': typeof AdminVariantsRoute
  '/': typeof PublicIndexRoute
  '/admin': typeof AdminIndexRoute
  '/api/public/sync-reviews': typeof ApiPublicSyncReviewsRoute
  '/menu/table/$tableId': typeof MenuTableTableIdRoute
  '/api/public/proxy/image': typeof ApiPublicProxyImageRoute
  '/api/public/proxy/video': typeof ApiPublicProxyVideoRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_public': typeof PublicRouteWithChildren
  '/admin': typeof AdminRouteWithChildren
  '/login': typeof LoginRoute
  '/_public/contact': typeof PublicContactRoute
  '/_public/gallery': typeof PublicGalleryRoute
  '/_public/menu': typeof PublicMenuRoute
  '/_public/reservation': typeof PublicReservationRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/gallery': typeof AdminGalleryRoute
  '/admin/menu': typeof AdminMenuRoute
  '/admin/reservations': typeof AdminReservationsRoute
  '/admin/reviews': typeof AdminReviewsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/tables': typeof AdminTablesRoute
  '/admin/templates': typeof AdminTemplatesRoute
  '/admin/variants': typeof AdminVariantsRoute
  '/_public/': typeof PublicIndexRoute
  '/admin/': typeof AdminIndexRoute
  '/api/public/sync-reviews': typeof ApiPublicSyncReviewsRoute
  '/menu/table/$tableId': typeof MenuTableTableIdRoute
  '/api/public/proxy/image': typeof ApiPublicProxyImageRoute
  '/api/public/proxy/video': typeof ApiPublicProxyVideoRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/login'
    | '/contact'
    | '/gallery'
    | '/menu'
    | '/reservation'
    | '/admin/audit'
    | '/admin/categories'
    | '/admin/gallery'
    | '/admin/menu'
    | '/admin/reservations'
    | '/admin/reviews'
    | '/admin/settings'
    | '/admin/tables'
    | '/admin/templates'
    | '/admin/variants'
    | '/admin/'
    | '/api/public/sync-reviews'
    | '/menu/table/$tableId'
    | '/api/public/proxy/image'
    | '/api/public/proxy/video'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/contact'
    | '/gallery'
    | '/menu'
    | '/reservation'
    | '/admin/audit'
    | '/admin/categories'
    | '/admin/gallery'
    | '/admin/menu'
    | '/admin/reservations'
    | '/admin/reviews'
    | '/admin/settings'
    | '/admin/tables'
    | '/admin/templates'
    | '/admin/variants'
    | '/'
    | '/admin'
    | '/api/public/sync-reviews'
    | '/menu/table/$tableId'
    | '/api/public/proxy/image'
    | '/api/public/proxy/video'
  id:
    | '__root__'
    | '/_public'
    | '/admin'
    | '/login'
    | '/_public/contact'
    | '/_public/gallery'
    | '/_public/menu'
    | '/_public/reservation'
    | '/admin/audit'
    | '/admin/categories'
    | '/admin/gallery'
    | '/admin/menu'
    | '/admin/reservations'
    | '/admin/reviews'
    | '/admin/settings'
    | '/admin/tables'
    | '/admin/templates'
    | '/admin/variants'
    | '/_public/'
    | '/admin/'
    | '/api/public/sync-reviews'
    | '/menu/table/$tableId'
    | '/api/public/proxy/image'
    | '/api/public/proxy/video'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  PublicRoute: typeof PublicRouteWithChildren
  AdminRoute: typeof AdminRouteWithChildren
  LoginRoute: typeof LoginRoute
  ApiPublicSyncReviewsRoute: typeof ApiPublicSyncReviewsRoute
  MenuTableTableIdRoute: typeof MenuTableTableIdRoute
  ApiPublicProxyImageRoute: typeof ApiPublicProxyImageRoute
  ApiPublicProxyVideoRoute: typeof ApiPublicProxyVideoRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public': {
      id: '/_public'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof PublicRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_public/': {
      id: '/_public/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof PublicIndexRouteImport
      parentRoute: typeof PublicRoute
    }
    '/admin/variants': {
      id: '/admin/variants'
      path: '/variants'
      fullPath: '/admin/variants'
      preLoaderRoute: typeof AdminVariantsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/templates': {
      id: '/admin/templates'
      path: '/templates'
      fullPath: '/admin/templates'
      preLoaderRoute: typeof AdminTemplatesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/tables': {
      id: '/admin/tables'
      path: '/tables'
      fullPath: '/admin/tables'
      preLoaderRoute: typeof AdminTablesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/reviews': {
      id: '/admin/reviews'
      path: '/reviews'
      fullPath: '/admin/reviews'
      preLoaderRoute: typeof AdminReviewsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/reservations': {
      id: '/admin/reservations'
      path: '/reservations'
      fullPath: '/admin/reservations'
      preLoaderRoute: typeof AdminReservationsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/menu': {
      id: '/admin/menu'
      path: '/menu'
      fullPath: '/admin/menu'
      preLoaderRoute: typeof AdminMenuRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/gallery': {
      id: '/admin/gallery'
      path: '/gallery'
      fullPath: '/admin/gallery'
      preLoaderRoute: typeof AdminGalleryRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/categories': {
      id: '/admin/categories'
      path: '/categories'
      fullPath: '/admin/categories'
      preLoaderRoute: typeof AdminCategoriesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/audit': {
      id: '/admin/audit'
      path: '/audit'
      fullPath: '/admin/audit'
      preLoaderRoute: typeof AdminAuditRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_public/reservation': {
      id: '/_public/reservation'
      path: '/reservation'
      fullPath: '/reservation'
      preLoaderRoute: typeof PublicReservationRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/menu': {
      id: '/_public/menu'
      path: '/menu'
      fullPath: '/menu'
      preLoaderRoute: typeof PublicMenuRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/gallery': {
      id: '/_public/gallery'
      path: '/gallery'
      fullPath: '/gallery'
      preLoaderRoute: typeof PublicGalleryRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/contact': {
      id: '/_public/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof PublicContactRouteImport
      parentRoute: typeof PublicRoute
    }
    '/menu/table/$tableId': {
      id: '/menu/table/$tableId'
      path: '/menu/table/$tableId'
      fullPath: '/menu/table/$tableId'
      preLoaderRoute: typeof MenuTableTableIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/sync-reviews': {
      id: '/api/public/sync-reviews'
      path: '/api/public/sync-reviews'
      fullPath: '/api/public/sync-reviews'
      preLoaderRoute: typeof ApiPublicSyncReviewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/proxy/video': {
      id: '/api/public/proxy/video'
      path: '/api/public/proxy/video'
      fullPath: '/api/public/proxy/video'
      preLoaderRoute: typeof ApiPublicProxyVideoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/proxy/image': {
      id: '/api/public/proxy/image'
      path: '/api/public/proxy/image'
      fullPath: '/api/public/proxy/image'
      preLoaderRoute: typeof ApiPublicProxyImageRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface PublicRouteChildren {
  PublicContactRoute: typeof PublicContactRoute
  PublicGalleryRoute: typeof PublicGalleryRoute
  PublicMenuRoute: typeof PublicMenuRoute
  PublicReservationRoute: typeof PublicReservationRoute
  PublicIndexRoute: typeof PublicIndexRoute
}

const PublicRouteChildren: PublicRouteChildren = {
  PublicContactRoute: PublicContactRoute,
  PublicGalleryRoute: PublicGalleryRoute,
  PublicMenuRoute: PublicMenuRoute,
  PublicReservationRoute: PublicReservationRoute,
  PublicIndexRoute: PublicIndexRoute,
}

const PublicRouteWithChildren =
  PublicRoute._addFileChildren(PublicRouteChildren)

interface AdminRouteChildren {
  AdminAuditRoute: typeof AdminAuditRoute
  AdminCategoriesRoute: typeof AdminCategoriesRoute
  AdminGalleryRoute: typeof AdminGalleryRoute
  AdminMenuRoute: typeof AdminMenuRoute
  AdminReservationsRoute: typeof AdminReservationsRoute
  AdminReviewsRoute: typeof AdminReviewsRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminTablesRoute: typeof AdminTablesRoute
  AdminTemplatesRoute: typeof AdminTemplatesRoute
  AdminVariantsRoute: typeof AdminVariantsRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAuditRoute: AdminAuditRoute,
  AdminCategoriesRoute: AdminCategoriesRoute,
  AdminGalleryRoute: AdminGalleryRoute,
  AdminMenuRoute: AdminMenuRoute,
  AdminReservationsRoute: AdminReservationsRoute,
  AdminReviewsRoute: AdminReviewsRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminTablesRoute: AdminTablesRoute,
  AdminTemplatesRoute: AdminTemplatesRoute,
  AdminVariantsRoute: AdminVariantsRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  PublicRoute: PublicRouteWithChildren,
  AdminRoute: AdminRouteWithChildren,
  LoginRoute: LoginRoute,
  ApiPublicSyncReviewsRoute: ApiPublicSyncReviewsRoute,
  MenuTableTableIdRoute: MenuTableTableIdRoute,
  ApiPublicProxyImageRoute: ApiPublicProxyImageRoute,
  ApiPublicProxyVideoRoute: ApiPublicProxyVideoRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
