// This file is automatically generated. Do not edit it directly.
// Server-side Supabase client with service role key - bypasses RLS.
// Use this for admin operations in server functions and server routes only.
// For user-authenticated queries (with RLS), use the auth middleware instead.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

function getEnv(key: string): string {
  // Vercel / Node: process.env is the primary source
  // Vite SSR: import.meta.env is the fallback (VITE_ prefixed vars)
  return (
    (typeof process !== 'undefined' && process.env?.[key]) ||
    (typeof (import.meta as any).env !== 'undefined' && (import.meta as any).env?.[key]) ||
    ''
  );
}

function createSupabaseAdminClient() {
  const SUPABASE_URL =
    getEnv('SUPABASE_URL') ||
    getEnv('VITE_SUPABASE_URL');

  const SUPABASE_SERVICE_ROLE_KEY =
    getEnv('SUPABASE_SERVICE_ROLE_KEY') ||
    // Fallback to anon/publishable key for local dev (read-only public ops work)
    getEnv('SUPABASE_PUBLISHABLE_KEY') ||
    getEnv('VITE_SUPABASE_PUBLISHABLE_KEY');

  if (!SUPABASE_URL || !SUPABASE_SERVICE_ROLE_KEY) {
    const missing = [
      ...(!SUPABASE_URL ? ['SUPABASE_URL'] : []),
      ...(!SUPABASE_SERVICE_ROLE_KEY ? ['SUPABASE_SERVICE_ROLE_KEY'] : []),
    ];
    // Log but do NOT throw at module init time — throw at call time instead
    // so the SSR page itself can still render (with empty data sections)
    console.error(
      `[Supabase] Missing environment variable(s): ${missing.join(', ')}. ` +
      'Add them to your Vercel project settings → Environment Variables.'
    );
    throw new Error(
      `Missing Supabase environment variable(s): ${missing.join(', ')}. ` +
      'Go to Vercel Dashboard → Project → Settings → Environment Variables and add SUPABASE_URL and SUPABASE_SERVICE_ROLE_KEY.'
    );
  }

  if (SUPABASE_SERVICE_ROLE_KEY === getEnv('VITE_SUPABASE_PUBLISHABLE_KEY') ||
      SUPABASE_SERVICE_ROLE_KEY === getEnv('SUPABASE_PUBLISHABLE_KEY')) {
    console.warn(
      '[Supabase] Using anon key instead of service_role key. Admin write operations will fail due to RLS.'
    );
  }

  return createClient<Database>(SUPABASE_URL, SUPABASE_SERVICE_ROLE_KEY, {
    auth: {
      storage: undefined,
      persistSession: false,
      autoRefreshToken: false,
    }
  });
}

let _supabaseAdmin: ReturnType<typeof createSupabaseAdminClient> | undefined;

// Server-side Supabase client with service role - bypasses RLS
// SECURITY: Only use this for trusted server-side operations, never expose to client code
// Import like: import { supabaseAdmin } from "@/integrations/supabase/client.server";
export const supabaseAdmin = new Proxy({} as ReturnType<typeof createSupabaseAdminClient>, {
  get(_, prop, receiver) {
    if (!_supabaseAdmin) _supabaseAdmin = createSupabaseAdminClient();
    return Reflect.get(_supabaseAdmin, prop, receiver);
  },
});

